server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get
        - id: payment_routh
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/getById/**  # 一个*号匹配单层路径，两个*号匹配多层路径
        - id: payment_ruth
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/list
#            - Before=2020-02-02T15:10:03.685+08:00[Asia/Shanghai]
#            - After=2020-02-02T15:10:03.685+08:00[Asia/Shanghai]
#            - Between=2020-02-02T15:10:03.685+08:00[Asia/Shanghai],2020-02-02T16:10:03.685+08:00[Asia/Shanghai]
#            - Cookie=username,zzyy     # cookie中带有username:zzyy这个键值对
#            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Query=username, \d+ # 要有参数名为username的参数，并且参数值为整数


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    # 表示将自己注册进eureka server
    register-with-eureka: true
    # 表示从eureka server抓取已有的注册信息
    fetch-registry: true
    service-url:
      # 集群
#      defaultZone: http://eureka1:7001/eureka,http://eureka2:7002/eureka
      # 单机
      defaultZone: http://eureka1:7001/eureka
