server:
  port: 7002

eureka:
  instance:
    hostname: eureka2  # eureka服务端的实例名称  在host文件中配置ip域名映射
  client:
    # 表示不向eureka注册自己
    register-with-eureka: false
    # 自己是注册中心
    fetch-registry: false
    service-url:
      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka1:7001/eureka/
      # 单机
#      defaultZone: http://eureka2:7002/eureka/
#  server:
  # 关闭eureka自我保护
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000