server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1 # 采集率
  cloud:
    nacos:
      discovery:
        server-addr: https://www.sloveo.com/
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
        clientIp: 127.0.0.1
      datasource:
        ds1:
          nacos:
            server-addr: 115.29.149.22:80
            groupId: DEFAULT_GROUP
            date-type: json
            rule-type: flow
            dataId: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: '*'