server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 115.29.149.22:80
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
        clientIp: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: '*'