server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        server-addr: 115.29.149.22:80
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
        clientIp: 127.0.0.1

# 消费者将要去访问的微服务的名称
service-url:
  nacos-user-service: http://nacos-payment-provider

management:
  endpoints:
    web:
      exposure:
        include: '*'