server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        server-addr: 115.29.149.22:81

management:
  endpoints:
    web:
      exposure:
        include: '*'