server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ch.entity

eureka:
  instance:
    instance-id: payment8002
    prefer-ip-address: true
    # eureka客户端向服务端发送心跳的时间
#    lease-renewal-interval-in-seconds: 1
    # eureka服务端在收到最后一次心跳后等待时间上限 超时剔除服务
#    lease-expiration-duration-in-seconds: 2
  client:
    # 表示将自己注册进eureka server
    register-with-eureka: true
    # 表示从eureka server抓取已有的注册信息
    fetch-registry: true
    service-url:
      # 集群
#      defaultZone: http://eureka1:7001/eureka,http://eureka2:7002/eureka
      # 单机
      defaultZone: http://eureka1:7001/eureka
