server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1 # 采集率
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        server-addr: https://www.sloveo.com/
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
        clientIp: 127.0.0.1

# 消费者将要去访问的微服务的名称
service-url:
  nacos-user-service: http://nacos-payment-provider

management:
  endpoints:
    web:
      exposure:
        include: '*'